core/build.gradle.kts
Fix: Add `HAVE_GETHOSTUUID=0` to `compilerOpts` resolving compiler error when compiling sqliteArm64Simulator
Error:
```
Exception in thread "main" java.lang.Error ...  'gethostuuid' is unavailable: not available on iOS
```
=> [Fix] Add missing `compilerOpts` to`cinterop` 

core/src/commonMain/kotlin/com/powersync/sync/StreamingSyncCheckpointDiff.kt
I saw this issue appear now that we fixed allowing `write_checkpoint` to be nullable.
```
SyncStream::streamingSync Error: kotlinx.serialization.MissingFieldException: Field 'write_checkpoint' is required for type with serial name 'com.powersync.sync.StreamingSyncCheckpointDiff', but it was missing
```
* Made `write_checkpoint` = null so that it is truly optional as explained in https://stackoverflow.com/questions/64796913/kotlinx-serialization-missingfieldexception. 
Note we could also implement this system wide to avoid similar issues in future https://github.com/Kotlin/kotlinx.serialization/blob/v1.3.0-RC/docs/json.md#explicit-nulls
=> fix: make field truly optional

core/src/commonMain/kotlin/com/powersync/db/PowerSyncDatabaseImpl.kt, core/src/commonMain/kotlin/com/powersync/db/ReadQueries.kt, core/src/commonMain/kotlin/com/powersync/db/WriteQueries.kt, core/src/commonMain/kotlin/com/powersync/db/internal/PsInternalDatabase.kt
Allow nullable fields in reads and writes
* Implemented allowing `Any?` type in executes and applied changes to accommodate this.
=> chore: allow nullable args in reads and writes

connectors/supabase/src/commonMain/kotlin/com/powersync/connector/supabase/SupabaseConnector.kt, core/src/commonMain/kotlin/com/powersync/connectors/PowerSyncCredentials.kt
`expiresAt` is an unused field and was only added for debugging purposes. As this is no longer necessary and converting Dates from Swift to Kotlin is a lot of a work it can be removed to avoid this. 
Removed all references to `expiresAt` field
=> chore: remove expiresAt field

PowerSync/gradle.properties
There is an error `Received status code 422 from server: Unprocessable Entity` when publishing as shown in this action https://github.com/powersync-ja/powersync-kotlin/actions/runs/9598875826/job/26471307117. Based on this stackoverflow https://stackoverflow.com/questions/64322121/publishing-github-packages-returns-422-error entry it appears that the artifact id must be lowercase to publish. This PR changes the artifact id to lowercase.
=> fix: 422 publishing error

core/build.gradle.kts, core/src/androidMain/kotlin/BuildConfig.kt, core/src/commonMain/kotlin/BuildConfig.kt, core/src/commonMain/kotlin/com/powersync/PowerSyncDatabaseFactory.kt, core/src/commonMain/kotlin/com/powersync/bucket/BucketStorage.kt, core/src/commonMain/kotlin/com/powersync/db/PowerSyncDatabaseImpl.kt, core/src/commonMain/kotlin/com/powersync/sync/SyncStatus.kt, core/src/commonMain/kotlin/com/powersync/sync/SyncStream.kt, core/src/commonMain/kotlin/com/powersync/utils/Log.kt, core/src/iosMain/kotlin/BuildConfig.kt, gradle/libs.versions.toml
Improve the logging experience for users. 
Currently, all the logs are exposed which may result in sensitive information being logged resulting in a security vulnerability. To improve this I have changed the current logger Canard to use touchlab's [Kermit](https://kermit.touchlab.co/docs/) logger and if a user does not provide a logger I have set some sensible log levels to be displayed when it is `debug` or `release` build. The reason for this is 
1. It allows the user to set the global logger settings
2. It is more popular which increases the likelihood of users already using it
3. The experience is now more aligned with the other SDK's
4. It is extendable by the user but has sensible defaults set if they opt not to
* Added a build config flag which is used to determine if it is a debug …
=> chore: improve logging

PowerSync/build.gradle.kts, core/src/commonMain/kotlin/com/powersync/connectors/PowerSyncBackendConnector.kt
When SKIE bridges the code from Kotlin to Swift it makes a few changes to suspend functions that have resulted in quite a few issues. 
The crux of the issue is that `async` functions in Swift are running on the main thread while `suspend` functions that are transformed using SKIE to Swift are run on a background thread. This results in transactions starting on the main thread while the database execute functions in the transaction are run on a background thread leading to deadlocks and changes being rejected as indicated by the audit report. Further this seems to have also had implications on token refreshes and once removed has fixed those issues.
This PR turns of SKIE changes to Kotlin `suspend` functions. From some manual testing on the demo app there does not appear to be any issue or …
=> chore: turn SKIE off for suspend functions

core/src/commonMain/kotlin/com/powersync/db/PowerSyncDatabaseImpl.kt, core/src/commonMain/kotlin/com/powersync/sync/SyncStream.kt
Stale credentials are being kept on disconnect.
Add `invalidateCredentials` to the `disconnect` function so that stale credentials are cleared when `disconnect` is called which should happen during `signOut`. 
https://github.com/user-attachments/assets/69d0d748-54f5-4d3d-ab84-31c0bc31f75c
=> fix: credentials not invalidating on disconnect

core/src/commonMain/kotlin/com/powersync/PowerSyncDatabase.kt, core/src/commonMain/kotlin/com/powersync/sync/SyncStream.kt
Make delays conform to other SDK's
Changed `crudThrottleMs` and `retryDelayMs` to match SDKs, i.e. 1000ms and 5000ms respectively.
=> chore: update delays

core/src/commonMain/kotlin/com/powersync/bucket/BucketStorage.kt, core/src/commonMain/kotlin/com/powersync/db/crud/CrudEntry.kt
An issue arose when we wanted to change a value from a non-null type to null in `uploadData` function. This was a result of opData always returning strings and therefore returning `"null"` and not `null`. The `uploadData` function tried to upload data to the postgres db which would result in for example:
```bash
Data upload error - retrying last entry: CrudEntry<3/3 PATCH todos/d6b6d112-e779-4389-a7b4-34c45808ecdc {completed=0, completed_at=null, completed_by=null}>, io.github.jan.supabase.exceptions.BadRequestRestException: invalid input syntax for type timestamp with time zone: "null"
```
Added a case to handle `null` values in `opData`.
Video shows values returning true when not null and false when null in the console. Also no errors are shown where previously the error above would be …
=> fix: handle null values in opData

README.md, core/src/commonMain/kotlin/com/powersync/bucket/BucketStorage.kt, core/src/commonMain/kotlin/com/powersync/db/PowerSyncDatabaseImpl.kt, core/src/commonMain/kotlin/com/powersync/db/Queries.kt, core/src/commonMain/kotlin/com/powersync/db/internal/InternalDatabase.kt, core/src/commonMain/kotlin/com/powersync/db/internal/PowerSyncTransaction.kt, core/src/commonMain/kotlin/com/powersync/db/internal/PowerSyncTransactionFactory.kt, demos/hello-powersync/composeApp/src/commonMain/kotlin/com/powersync/demos/PowerSync.kt, demos/supabase-todolist/shared/src/commonMain/kotlin/com/powersync/demos/powersync/List.kt, demos/supabase-todolist/shared/src/commonMain/kotlin/com/powersync/demos/powersync/Todo.kt
Adopt callback pattern for `readTransaction` and `writeTransaction`. 
Changed `readTransaction` and `writeTransaction` functionality to use a callback such that users can now use for example
db.writeTransaction { tx ->
tx.execute()
tx.get()
...
}
https://github.com/user-attachments/assets/75720202-95f3-45eb-b939-cce6bde63cff
=> chore: use callback in transactions

CHANGELOG.md, README.md, core/README.md, demos/hello-powersync/README.md, demos/supabase-todolist/README.md, demos/supabase-todolist/shared/build.gradle.kts, gradle.properties
=> chore: release beta 1

core/src/commonMain/kotlin/com/powersync/db/schema/Schema.kt, core/src/commonTest/kotlin/com/powersync/db/schema/SchemaTest.kt, core/src/commonTest/kotlin/com/powersync/db/schema/TableTest.kt
Schema is not running validation on creation
* Added validation on schema creation
* Added testing for Schema class
=> fix: schema not running table validation

core/src/commonMain/kotlin/com/powersync/bucket/BucketStorage.kt, core/src/commonMain/kotlin/com/powersync/db/PowerSyncDatabaseImpl.kt, core/src/commonMain/kotlin/com/powersync/sync/StreamingSyncRequest.kt, core/src/commonMain/kotlin/com/powersync/sync/SyncStatus.kt, core/src/commonMain/kotlin/com/powersync/sync/SyncStream.kt, core/src/commonTest/kotlin/com/powersync/sync/StreamingSyncRequestTest.kt, demos/supabase-todolist/gradle/libs.versions.toml, demos/supabase-todolist/iosApp/iosApp.xcodeproj/project.pbxproj, gradle/libs.versions.toml
Add hasSynced, clientId and version check
* Add `hasSynced` functionality to check if a sync has occurred
* Add client id to request
* Add version check
I have run the app and confirmed 
1. hasSynced is updated when sync occurs
2. client id is included
3. version check occurs and works (I used a version older than 2.0.0)
=> feat: add client id to requests, add hasSynced and version check

core/src/commonMain/kotlin/com/powersync/db/PowerSyncDatabaseImpl.kt
A null pointer exception is thrown when sync has not yet happened in `updateHasSynced`. When initially testing I was logged in and everything worked as expected but after deleting the app I ran into this issue.
Added a `try catch` to catch the case when the cursor receives a `null` value in:
```
val timestamp = internalDb.getOptional("SELECT powersync_last_synced_at() as synced_at", null) { cursor ->
cursor.getString(0)!!
}
```
=> fix: null pointer exception when sync has not happened yet

demos/supabase-todolist/shared/build.gradle.kts
If a user has an old `Podfile.lock` with a `powersync-sqlite-core` version that is less than 0.2.0 they will see an error as we now require them to use a version of `powersync-sqlite-core` > 0.2.0.
* Added a version in cocoapods section of build.gradle.kts pod so that users will be required to upgrade their `powersync-sqlite-core` pod. The downside of this is that we can only set exact values. Therefore we will need to update this value in future. However, we could remove it once we are sure all users are using a version greater than 0.2.0 as it will then download the latest version.
=> fix: required powersync sqlite core version not set

core/src/commonMain/kotlin/com/powersync/db/PowerSyncDatabaseImpl.kt, dialect/README.md, dialect/src/main/kotlin/com/powersync/sqlite/PowerSyncDialect.kt, persistence/src/commonMain/sqldelight/com/persistence/Powersync.sq
Implement new `powersync_clear()` function and update hasSynced status in `disconnectAndClear`.
* Replaced old clearing implementation with the new `powersync_clear()` in `disconnectAndClear` function. This required a change to the `dialect` module to include `powersync_clear` as a valid type and the `PowerSync.sq` file used to load the custom PowerSync functions as queries in the `persistence` module.
* Added an update to the currentStatus to update `hasSynced` to `false` and `lastSynced` to `null`
https://github.com/user-attachments/assets/4324dfbe-fdb9-415d-95e8-ae1256ff248d
=> chore: add changes to disconnectAndClear

persistence/build.gradle.kts
Currently `persistence` module has no `minSdk` version set which results in an error being shown. This adds a minSdk version to the `build.gradle.kts` file of `persistence` module to avoid seeing this error.
=> chore(persistence): add minSdk

.gitignore, build.gradle.kts, compose/build.gradle.kts, demos/hello-powersync/build.gradle.kts, demos/hello-powersync/composeApp/build.gradle.kts, demos/hello-powersync/composeApp/composeApp.podspec, demos/hello-powersync/gradle/wrapper/gradle-wrapper.properties, demos/hello-powersync/iosApp/Podfile.lock, demos/hello-powersync/iosApp/iosApp.xcodeproj/project.pbxproj, demos/supabase-todolist/androidApp/build.gradle.kts, demos/supabase-todolist/build.gradle.kts, demos/supabase-todolist/desktopApp/build.gradle.kts, demos/supabase-todolist/gradle/libs.versions.toml, demos/supabase-todolist/iosApp/iosApp.xcodeproj/project.pbxproj, demos/supabase-todolist/shared/build.gradle.kts, gradle/libs.versions.toml
Kotlin 2.0.20 is out and fixes issues related to using Kotlin with XCode 16 which has required us upgrading from 1.9.24.
* Needed to add and use new compose compiler plugin (https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-compiler.html#migrating-a-compose-multiplatform-project)
* Removed `kotlinCompilerExtensionVersion` from `hello-powersync` as this is no longer required (https://android-developers.googleblog.com/2024/04/jetpack-compose-compiler-moving-to-kotlin-repository.html)
* Needed to move to SKIE `0.9.0-RC5` as this supports Kotlin 2.0.20
* Removed unused dependencies
* `hello-powersync` required a gradle upgrade to 8.7 in order to run
* Git Ignored `.kotlin` folders
* Changed from `api` to `implelementation` where possible in `demos`
1. Ran both …
=> chore: upgrade to kotlin 2.0.20

core/src/commonMain/kotlin/com/powersync/bucket/BucketStorage.kt, core/src/commonMain/kotlin/com/powersync/db/PowerSyncDatabaseImpl.kt, core/src/commonMain/kotlin/com/powersync/sync/SyncStream.kt, demos/android-supabase-todolist/app/src/main/java/com/powersync/androidexample/powersync/List.kt, demos/supabase-todolist/shared/src/commonMain/kotlin/com/powersync/demos/powersync/List.kt
1. Fix the issue where client IDs were not matching leading to down syncs not being shown on the client app.
2. Fix `updateObjectsFromBuckets` always returning true.
* There was an erroneously included `'` at the end of `clientId` when hitting the `write-checkpoint` endpoint which I have now removed.
* Moved to `writeTransaction` in `updateLocalTarget` function as there is a write occurring in the transaction.
* Moved to use new `delete_pending_buckets` operation.
* `updateObjectsFromBuckets` now returns the response from
```
val res = tx.get("select last_insert_rowid()") { cursor ->
cursor.getLong(0)!!
}
```
as opposed to the execute
```
res = tx.execute(
"INSERT INTO powersync_operations(op, data) VALUES(?, ?)",
listOf("sync_local", "")
)
```
which always returned 1 row updated and …
=> fix: down syncs not being reflected in client app

core/src/commonMain/kotlin/com/powersync/db/PowerSyncDatabaseImpl.kt, demos/supabase-todolist/shared/build.gradle.kts, gradle/libs.versions.toml
Update to `powersync-sqlite-core: 0.3.0`
* Updated dependencies to use latest version
* Made change to version check to allow for versions greater than 2
Ran the demo app and did the some crud operations as well as some changes from Supabase to confirm that changes are synced down correctly.
=> chore: update powersync sqlite core

core/src/commonMain/kotlin/com/powersync/sync/SyncStatus.kt, demos/supabase-todolist/shared/src/commonMain/kotlin/com/powersync/demos/App.kt, demos/supabase-todolist/shared/src/commonMain/kotlin/com/powersync/demos/screens/HomeScreen.kt
There was an issue where `hasSynced` was being reset after becoming true. This issue was due to the `update` function in the `SyncStatus` class using the `copy` method and expecting default values to be persisted. However when the `update` function is run and `copy` is invoked it does not know about the default values in the `update` function so it overwrites the previous values with null.
This fixes the issue by not relying on default values from the `update` function.
Previously
```
status = { connected: true, hasSynced: true }
status.update(connected:false)
status = { connected false, hasSynced: null }
``` 
Now
```
status = { connected: true, hasSynced: true }
status.update(connected:false)
status = { connected false, hasSynced: true }
``` 
I have also included an example …
=> fix: sync status not updating correctly

CHANGELOG.md, core/src/commonMain/kotlin/com/powersync/db/PowerSyncDatabaseImpl.kt, gradle.properties
This aligns the logic for Custom Write Checkpoints with the JS and Dart SDKs by correcting an error in the logical tests.
For reference see:
- Dart [implementation](https://github.com/powersync-ja/powersync.dart/blob/fb2f312247d44f74efaaa097c090190f9514e607/packages/powersync/lib/src/database/powersync_db_mixin.dart#L406)
- JS [implementation](https://github.com/powersync-ja/powersync-js/blob/30825f3e6137a86cf37a2e393e9e193bcf1debc4/packages/common/src/client/AbstractPowerSyncDatabase.ts#L577)
=> fix: custom write checkpoint logic

PowerSync/build.gradle.kts
The setting to disable Skie SuspendInterop was removed in #75, this causes a compile time error in the Beta 6 as it requires the `__` prefix when overriding suspend functions in Swift see this [link](https://skie.touchlab.co/features/suspend#overriding-suspend-functions) for more details.
This PR disables SuspendInterop as it was in Beta 5.
- Disable SuspendInterop for Skie
I tested this locally by generating a SPM dev build using the gradle script (`spmDevBuild`) and linking the `powersync-kotlin-swift-demo` to the local package. I confirmed that it fixes compile time errors and the demo runs as expected.
=> Disable Skie SuspendInterop

.github/workflows/deploy.yml
This resolves the issue of kmmbridge job being cancelled for old macos machine version being used. More info here https://github.com/touchlab/KMMBridgeGithubWorkflow/releases/tag/v1.2
=> chore: update kmmbridge action

PowerSyncKotlin/build.gradle.kts
Previously, the project name matched where the file was stored on maven central which results in this error https://github.com/powersync-ja/powersync-kotlin/actions/runs/12235887342/job/34128918656. Given the name of the project has changed this is no longer the case. This fixes the name to match what is in maven i.e. `powersync-...`
=> fix: ci pipeline after name change

CHANGELOG.md, gradle.properties
There's a conflict on deployment as Beta 10 was released in Maven but did not complete. This updates the version to avoid the conflict and will result in a complete release. See error here https://github.com/powersync-ja/powersync-kotlin/actions/runs/12238823826/job/34138685054
=> chore: update version to fix pipeline

CHANGELOG.md, core/src/commonMain/kotlin/com/powersync/bucket/BucketStorageImpl.kt
There is an issue in the Swift SDK where this happens sporadically `Uncaught Kotlin exception: kotlin.IllegalStateException: Transaction objects (TransactionWithReturn and TransactionWithoutReturn) must be used
only within the transaction lambda scope.`. My hunch is that this is as a result of the bucketStorage not using the correct context. This changes the `writeTransaction` to use the transaction context passed as a callback which should fix the issue.
=> fix: transaction resulting in race condition when not using the correct context

CHANGELOG.md, core/src/iosMain/kotlin/com/powersync/DatabaseDriverFactory.ios.kt, gradle.properties
We were sporadically encountering `IllegalStateException` with the message "Transaction objects must be used only within the transaction lambda scope." This typically indicates a race condition where transaction objects are being accessed across different threads or coroutine contexts. I initially thought it was because of a transaction in BucketStorageImpl was using the wrong context (which was addressed in this PR https://github.com/powersync-ja/powersync-kotlin/pull/89) but this was not the case as the issue persisted.
Database operations were not consistently running on the same dispatcher, which could lead to transaction objects being accessed from different threads. SQLDelight requires transaction operations to maintain thread confinement for safety.
Added a dedicated IO dispatcher …
=> fix: race condition in transaction

connectors/supabase/src/commonMain/kotlin/com/powersync/connector/supabase/SupabaseConnector.kt
Add more information about fatal upload data error
=> chore: add documentation for fatal error

CHANGELOG.md, core/src/commonMain/kotlin/com/powersync/db/PowerSyncDatabaseImpl.kt, core/src/iosMain/kotlin/com/powersync/DatabaseDriverFactory.ios.kt, gradle.properties
* Revert scope change from Beta 13 as this did not resolve the race condition error. This was erroneously thought to be the issue but instead added no value and produced no results.
* Update to Beta 14
=> chore: revert changes and update version

.github/workflows/deploy.yml, .github/workflows/test.yml
The Windows default shell does not support multi-line commands.
This updates the CI to :
- Run JVM tests on Linux, Mac & Windows
- Update run scripts to use the Bash shell (which supports muilti-line commands on all platforms)
=> Fix Windows deployment CI and add Windows testing

CHANGELOG.md, core/src/commonMain/kotlin/com/powersync/db/schema/Table.kt, core/src/commonTest/kotlin/com/powersync/db/schema/TableTest.kt, demos/supabase-todolist/shared/build.gradle.kts, gradle.properties, gradle/libs.versions.toml
Update `powersync-sqlite-core` package
=> chore: update powersync-sqlite-core

core/build.gradle.kts, core/src/jvmMain/kotlin/com/powersync/ExtractLib.kt
For some reason, the call-kmmbridge-publish job [installs an x64 JDK](https://github.com/powersync-ja/powersync-kotlin/actions/runs/12684995488/job/35355117625#step:12:6) on [an arm64 Mac OS runner](https://github.com/powersync-ja/powersync-kotlin/actions/runs/12684995488/job/35355117625#step:1:8). I'm guessing that it's because [KMMBridgeGithubWorkflow](https://github.com/touchlab/KMMBridgeGithubWorkflow) (which is deprecated by the way) [uses actions/setup-java@v2](https://github.com/touchlab/KMMBridgeGithubWorkflow/blob/f98a8b44a278cbea152e8ef1571f7e2054863188/.github/workflows/faktorybuildautoversion.yml#L108C15-L108C36), when current version of [actions/setup-java](https://github.com/actions/setup-java) is v4.
This led to the realization that some JVM [use the identifier …
=> Fix: on Intel x64, os.arch is either amd64 or x86_64 depending on the JVM.

CHANGELOG.md, core/src/commonMain/kotlin/com/powersync/PowerSyncDatabase.kt, core/src/commonMain/kotlin/com/powersync/db/PowerSyncDatabaseImpl.kt, core/src/commonMain/kotlin/com/powersync/db/internal/InternalDatabase.kt, core/src/commonMain/kotlin/com/powersync/db/internal/InternalDatabaseImpl.kt, demos/hello-powersync/iosApp/iosApp.xcodeproj/project.pbxproj, gradle.properties
Add the `close` method to public-facing API based on the requirement mentioned here https://github.com/powersync-ja/powersync-kotlin/issues/100.  The `close` method first disconnects and then closes the connection.
Ran the Supabase demo and ran `db.close()`
=> feat: expose close method

CHANGELOG.md, core/src/commonMain/kotlin/com/powersync/sync/SyncStream.kt, core/src/commonTest/kotlin/com/powersync/sync/SyncStreamTest.kt
This aims to resolve https://github.com/powersync-ja/powersync-kotlin/issues/102 where credentials are invalidated even though there is no network. It appears this was included before invalidation was properly handled and can be removed.
=> feat: do not invalidate credentials on io error

core/src/jvmNative/cpp/sqlite_bindings.cpp
Fixes the startup issue on Windows.
=> Adds JNIExport to powersync_init so that it is exported in the Windows DLL

core/src/androidMain/kotlin/com/powersync/DatabaseDriverFactory.android.kt, core/src/commonMain/kotlin/com/powersync/bucket/BucketStorage.kt, core/src/commonMain/kotlin/com/powersync/bucket/BucketStorageImpl.kt, core/src/commonMain/kotlin/com/powersync/db/PowerSyncDatabaseImpl.kt, core/src/commonMain/kotlin/com/powersync/db/Queries.kt, core/src/commonMain/kotlin/com/powersync/db/internal/InternalDatabase.kt, core/src/commonMain/kotlin/com/powersync/db/internal/InternalDatabaseImpl.kt, core/src/commonMain/kotlin/com/powersync/db/internal/InternalSchema.kt, core/src/commonMain/kotlin/com/powersync/db/internal/PowerSyncTransaction.kt, core/src/iosMain/kotlin/com/powersync/DatabaseDriverFactory.ios.kt, core/src/jvmMain/kotlin/com/powersync/DatabaseDriverFactory.jvm.kt, persistence/build.gradle.kts
* Remove async from sqldelight config
* Remove suspend from the transaction block and methods available on the PowerSyncTransaction interface
* Some access cleanup to ensure all direct db access is handled by `InternalDatabaseImpl`
* Move calls to the actual db off of caller thread inside `InternalDatabaseImpl`
=> Synchronized transactions

CHANGELOG.md, docs/MavenCentral.md, gradle.properties
This updates the SDK to version 18 which includes a breaking change to `readTransaction` and `writeTransaction` where the callback is no longer asynchronous.
This also includes documentation for the internal dev team on how to create and update the signing keys used to validate the Maven Central packages.
=> chore: update to BETA 18 and add maven central docs

CHANGELOG.md, gradle.properties
Update to Beta 19 which will then include the SQL driver updates to allow to get a column by name using cursor
=> chore: update version to BETA 19

CHANGELOG.md, core/src/commonMain/kotlin/com/powersync/db/SqlCursor.kt, demos/android-supabase-todolist/app/src/main/java/com/powersync/androidexample/powersync/List.kt, demos/android-supabase-todolist/app/src/main/java/com/powersync/androidexample/powersync/Todo.kt, demos/hello-powersync/composeApp/src/commonMain/kotlin/com/powersync/demos/PowerSync.kt, demos/supabase-todolist/shared/src/commonMain/kotlin/com/powersync/demos/powersync/List.kt, demos/supabase-todolist/shared/src/commonMain/kotlin/com/powersync/demos/powersync/Todo.kt, gradle.properties
* Add additional SqlCursor functions `getStringOptional`, `getLongOptional`, `getDoubleOptional`, `getBooleanOptional` and `getBytesOptional` when using the column name as a parameter which return optional types. 
* `getString`, `getLong`, `getBytes`, `getDouble` and `getBoolean` used with the column name parameter will now throw an error for non-null values and expect a non-optional return type
* Throw errors for invalid columns on all cursor functions that use the column name parameter
* Update version to Beta20
Previously you would need to assert types and cast
```kotlin
return Todo(
id: cursor.getString(name: "id")!,
photoId: cursor.getString(name: "photo_id"),
isComplete: cursor.getBoolean(name: "completed")! as! Bool,
)
```
now you can use this:
```kotlin
return Todo(
id: …
```
=> feat: add SqlCursor function improvements

docs/Release.md
Includes a guide on how to make a release. This is for internal use.
=> docs: add release guide

CHANGELOG.md, core/src/commonMain/kotlin/com/powersync/db/PowerSyncDatabaseImpl.kt, gradle.properties
Fix issue in `updateHasSynced` where null timestamp was allowed through. The issue was that `currentStatus.hasSynced` is initialized to `null` and not `false` so this check `if (hasSynced != currentStatus.hasSynced)` was always true.
Tested in Swift SDK and ran the supabase todolist app
=> fix: null pointer in updateHasSynced

CHANGELOG.md, core/src/commonMain/kotlin/com/powersync/db/PowerSyncDatabaseImpl.kt, core/src/commonMain/kotlin/com/powersync/db/Queries.kt, core/src/commonMain/kotlin/com/powersync/db/internal/InternalDatabaseImpl.kt, core/src/commonMain/kotlin/com/powersync/db/internal/PowerSyncTransaction.kt, gradle.properties
Make `execute` throwable in Swift so users of the Swift SDK can handle errors thrown in the `execute` function
See Swift PR https://github.com/powersync-ja/powersync-swift/pull/21 for new tests included to confirm this
=> chore: make execute throwable in swift

Package.swift, core/src/androidMain/kotlin/com/powersync/DatabaseDriverFactory.android.kt, core/src/commonMain/kotlin/com/powersync/db/internal/InternalDatabaseImpl.kt, core/src/iosMain/kotlin/com/powersync/DatabaseDriverFactory.ios.kt, core/src/jvmMain/kotlin/com/powersync/DatabaseDriverFactory.jvm.kt, demos/hello-powersync/composeApp/src/androidMain/AndroidManifest.xml, demos/hello-powersync/composeApp/src/androidMain/res/xml/network_security_config.xml, persistence/src/jvmMain/kotlin/com/powersync/persistence/driver/JdbcPreparedStatement.kt
The current watch query is prone to inconsistent issues. This issue arises because the SQLite commit hook transaction notifies listeners about a change before the transaction has been fully committed. Therefore a table update would fire and cause the watch query to re-run before the actual commit had taken place. This could result in timing issues as the query may not yet return with the new data as the transaction commit had not been completed.
This PR resolves this issue by accumulating table changes and only emitting a table update (which results in the watch query re-running) once a `writeTransaction` or `execute` has been completed.
The recommendation from this PR https://github.com/powersync-ja/powersync-kotlin/pull/121/files is also included.
There was an issue with the JDBC driver …
=> chore: improve watch query

core/src/commonMain/kotlin/com/powersync/db/Functions.kt
Just like in https://github.com/powersync-ja/powersync-kotlin/pull/104#discussion_r1916084097 , you should never catch `CancellationException`
=> Avoid catching CancellationException in `runWrappedSuspending`

.github/workflows/deploy.yml, CHANGELOG.md, core/build.gradle.kts, gradle.properties
First, this adapts the release workflow after the changes in https://github.com/powersync-ja/powersync-kotlin/pull/129: Since we're not compiling native code for the JVM release anymore, we don't need separate builds for cross-platform support either. We just need to make sure that the downloaded binaries for the core SQLite extensions are present for all platforms we support.
For this, I ran `./gradlew -Ppowersync.binaries.allPlatforms="true" publishAllPublicationsToSonatypeLocalRepository` manually and validated that the emitted `core-jvm-1.0.0-BETA26.jar` contains all the libraries we need.
Apart from that change, this is a regular version bump.
=> Prepare release for 1.0.0-BETA26

plugins/sonatype/src/main/kotlin/com/powersync/plugins/sonatype/SonatypeCentralExtension.kt
In 3a57b1b6a8dbe11f25faeed2b81c2132c59fa45c, I've changed the destination for the publishing tasks from a per-project directory to a single directory for the entire project. This is useful for me to test that publishing is working locally. Unfortunately, I overlooked that the rest of our Sonatype publishing pipeline depends on these per-project files 🙃 
This reverts that change, which should fix the release pipeline.
=> Fix release pipeline

demos/android-supabase-todolist/README.md, demos/supabase-todolist/README.md
Expand the readme of the Android and KMP demos to mention sync rules using bucket priorities. These aren't mentioned by the simple guide explaining how to use PowerSync with Supabase, so mentioning them in the readme points out that the feature exists and how to enable it.
The code works with both definitions without changes.
=> Mention bucket priorities on demo readme

.gitignore, CHANGELOG.md, core-tests-android/src/androidTest/java/com/powersync/AndroidDatabaseTest.kt, core/src/commonMain/kotlin/com/powersync/PsSqlDriver.kt, core/src/commonMain/kotlin/com/powersync/bucket/BucketStorageImpl.kt, core/src/commonMain/kotlin/com/powersync/db/PowerSyncDatabaseImpl.kt, core/src/commonMain/kotlin/com/powersync/db/Queries.kt, core/src/commonMain/kotlin/com/powersync/db/internal/InternalDatabase.kt, core/src/commonMain/kotlin/com/powersync/db/internal/InternalDatabaseImpl.kt, core/src/commonMain/kotlin/com/powersync/utils/AtomicMutableSet.kt, core/src/commonMain/kotlin/com/powersync/utils/ThrottleFlow.kt, core/src/commonTest/kotlin/com/powersync/bucket/BucketStorageTest.kt, core/src/commonTest/kotlin/com/powersync/utils/JsonTest.kt, demos/supabase-todolist/androidApp/src/androidMain/AndroidManifest.xml, demos/supabase-todolist/androidApp/src/main/res/xml/network.xml, demos/supabase-todolist/androidApp/src/main/res/xml/network_security_config.xml
This PR improves the watched query logic by optimizing table update handling, enhancing thread safety, and simplifying the implementation.
- Table changes in a transaction are now tracked using a `Set`, preventing redundant entries. Since SQLite emits an update per row, the previous implementation could accumulate large arrays of duplicate table changes.
- Resolves [issue #135](https://github.com/powersync-ja/powersync-kotlin/issues/135), where the current driver’s pending update storage was not thread-safe.
- The pending table changes set is now protected with Mutex locks.
- Replaces the existing SQLDelight watched query interface with a simpler, Flow-based solution.
- The new approach leverages the internal database’s `getAll` method instead of the driver’s synchronous methods.
- Table …
=> Improve Watch Queries

CHANGELOG.md, core/src/commonIntegrationTest/kotlin/com/powersync/SyncIntegrationTest.kt, core/src/commonMain/kotlin/com/powersync/db/PowerSyncDatabaseImpl.kt, core/src/commonMain/kotlin/com/powersync/sync/SyncStream.kt, demos/supabase-todolist/shared/src/commonMain/kotlin/com/powersync/demos/App.kt, demos/supabase-todolist/shared/src/commonMain/kotlin/com/powersync/demos/components/WifiIcon.kt, demos/supabase-todolist/shared/src/commonMain/kotlin/com/powersync/demos/screens/HomeScreen.kt, demos/supabase-todolist/shared/src/commonMain/kotlin/com/powersync/demos/screens/TodosScreen.kt, gradle.properties
This fixes the sync status indicator which did not emit any updates for `uploading` or `downloading`. 
Sync status updates for uploading or downloading can be quite fast. The demo has been updated to debounce the flow. A nicer UI might be to trigger some animation based off uploading/downloading. 
https://github.com/user-attachments/assets/a271d2fd-dddb-4750-91ef-332cbdc5796e
=> [Fix] Sync Status Updates

core/build.gradle.kts, core/src/iosMain/kotlin/com/powersync/DatabaseDriverFactory.ios.kt, demos/supabase-todolist/iosApp/iosApp.xcodeproj/project.pbxproj, gradle/libs.versions.toml, persistence/build.gradle.kts, settings.gradle.kts, static-sqlite-driver/README.md, static-sqlite-driver/build.gradle.kts, static-sqlite-driver/src/nativeTest/kotlin/SmokeTest.kt
All our client SDKs need the PowerSync core extension to be loaded to work. On Apple platforms however, SQLite extension loading is disabled. This means that our SDK must not link the SQLite library from the platform, and instead link a custom version compiled with extension support.
This:
1. Removes the last remnants of native builds in the `:core` project. We don't need it for Android since we're now using sqlite-jdbc. We also don't need it for iOS since we can call the cinterop methods exposed from the SQLiter dependency.
2. Disables linking SQLite with the option provided by SQLDelight (since that one uses the one from the system).
3. Adds a new project whose only purpose is to compile `sqlite3` into a static archive. This archive is then included on a cinterop definition. This makes …
=> Link SQLite statically on native platforms

gradle.properties
Reverts powersync-ja/powersync-kotlin#152
Looking at the CI failure, the option may be less safe than I thought. Definitely something to investigate at some point, reverting that sounds like the easiest option for now.
=> Revert "Enable `org.gradle.parallel` option"

CHANGELOG.md, core/src/commonIntegrationTest/kotlin/com/powersync/SyncIntegrationTest.kt, core/src/commonMain/kotlin/com/powersync/db/PowerSyncDatabaseImpl.kt, core/src/commonMain/kotlin/com/powersync/sync/SyncStatus.kt, core/src/commonTest/kotlin/com/powersync/sync/SyncStreamTest.kt, core/src/commonTest/kotlin/com/powersync/testutils/MockSyncService.kt
The jobs to download and upload data (as well as the one forwarding sync status changes) are all operating independently from each other, which can potentially cause issues stopping these jobs as once.
This adopts a `SupervisorJob` for the three, allowing us to cancel just one job in `disconnect` that's guaranteed to get them all.
I've also slightly refactored our test client so that it properly forwards cancellations (when we cancel the sync jobs, that propagates to `SyncStream.streamingSyncRequest` in the `request.execute` block). With the mock HTTP engine from ktor we unfortunately have no access to that scope, but by implementing a fairly trivial custom engine we can implement the same functionality while also reporting downstream listeners being cancelled.
This then allows testing …
=> Use structured concurrency for sync jobs

CHANGELOG.md, core/src/iosMain/kotlin/com/powersync/DatabaseDriverFactory.ios.kt
We currently create multiple readonly connections via the iOS driver. The iOS driver attempts to run schema migrations whenever a driver is created. It looks like these migrations are not synchronized internally. This causes errors of the form
```
Sqlite operation failure database is locked attempted to run migration and failed. closing connection
```
See example failed [test](https://github.com/powersync-ja/powersync-kotlin/actions/runs/14302972547/job/40081077924?pr=162)
This changeset avoids attempting to run migrations on read only drivers.
=> [Fix] IOS Migrations

CHANGELOG.md, core/src/jvmMain/kotlin/com/powersync/DatabaseDriverFactory.jvm.kt, core/src/jvmMain/kotlin/com/powersync/ExtractLib.kt
For JVM we currently find the PowerSync SQLite core resource's path then copy it to a temporary file. The temporary file is used when loading the extension in SQLite. The temporary file is deleted on process shutdown. 
https://github.com/powersync-ja/powersync-kotlin/issues/161 raised that on Windows an issue occurs when deleting the temporary file.
It looks like this method, of using a temporary file, was used in order to resolve the extension's path in a format compatible with Windows. Typically the `R::class.java.getResource(path)` result is of the format `/c:/...` which does not seem to work as an extension path in SQLite.
The logic has been updated to avoid the use of temporary files altogether. The binary resource file path is now used to load the SQLite extension.
=> [JVM Windows] Process shutdown bug

.github/workflows/test.yml, CHANGELOG.md, core/build.gradle.kts, core/src/commonIntegrationTest/kotlin/com/powersync/DatabaseTest.kt, core/src/commonIntegrationTest/kotlin/com/powersync/SyncIntegrationTest.kt, core/src/commonMain/kotlin/com/powersync/db/PowerSyncDatabaseImpl.kt, core/src/commonMain/kotlin/com/powersync/sync/SyncStream.kt, core/src/commonTest/kotlin/com/powersync/TestConnector.kt, core/src/commonTest/kotlin/com/powersync/sync/SyncStreamTest.kt, core/src/commonTest/kotlin/com/powersync/testutils/MockSyncService.kt
This is the Kotlin port of https://github.com/powersync-ja/powersync-js/pull/558, see that PR for a more complete description.
I also had to fix some other quirks in the sync implementation here, notably:
1. The `triggerCrudUpload()` call when receiving keep-alive messages used to block the entire sync stream from receiving subsequent lines until the upload was completed. This changes that to spawn an async job that is not awaited (the trigger listening on `ps_crud` will still await this though).
2. There was no way to abort sync iterations (used e.g. for checkpoints with a checksum mismatch). This adds that functionality.
=> Fix checkpoints during uploads not being applied

CHANGELOG.md, gradle.properties
This adopts the changelog and the version in `gradle.properties` to prepare for a release run.
=> Prepare 1.0.0-BETA29 release

CHANGELOG.md, core/src/commonIntegrationTest/kotlin/com/powersync/SyncIntegrationTest.kt, core/src/commonIntegrationTest/kotlin/com/powersync/testutils/TestUtils.kt, core/src/commonMain/kotlin/com/powersync/PowerSyncDatabaseFactory.kt, core/src/commonMain/kotlin/com/powersync/db/PowerSyncDatabaseImpl.kt, core/src/commonMain/kotlin/com/powersync/sync/SyncStream.kt, core/src/commonTest/kotlin/com/powersync/sync/SyncStreamTest.kt, gradle.properties
`PowerSyncDatabaseImpl.connect` used to call `waitReady()` inside of `mutex.withLock`. That's unfortunate, because `initialize` also acquires the mutex in `updateSchemaInternal`. So, when calling `connect()` immediately after creating a database, there's a potential for a deadlock. The mutex must only be acquired after waiting for the database to be initialized.
To validate the fix, I've migrated the sync tests to stop calling `connectInternal` and instead use the public `connect` method. This requires customizing the HTTP client engine passed to the sync engine, for which I've created an (internal) method next to the `PowerSyncDatabase` factory method. 
Closes https://github.com/powersync-ja/powersync-kotlin/issues/169.
=> Fix deadlock when connecting after opening database

CHANGELOG.md, README.md, connectors/supabase/src/commonMain/kotlin/com/powersync/connector/supabase/SupabaseConnector.kt, core/src/commonIntegrationTest/kotlin/com/powersync/testutils/TestUtils.kt, core/src/commonMain/kotlin/com/powersync/connectors/PowerSyncCredentials.kt, core/src/commonMain/kotlin/com/powersync/sync/SyncStream.kt, core/src/commonTest/kotlin/com/powersync/TestConnector.kt, core/src/commonTest/kotlin/com/powersync/sync/SyncStreamTest.kt
This removes an unnecessary `User-Id` header which is currently being added to PowerSync service requests. 
This header has not been used by the service for a long time. 
The parameter in `PowerSyncCredentials` has been deprecated.
=> Remove User Id header

plugins/sonatype/src/main/kotlin/com/powersync/plugins/sonatype/SonatypeCentralUploadPlugin.kt
The Gradle plugin we use for publishing will automatically depend on `dokkaHtml` to include the outputs of that task as a javadoc jar. That's generally nice, but not helpful for us because our subprojects apply Dokka without building independent documentation sites (we apply Dokka on the root project to build a single site for everything).
So, disable that and use an empty javadoc jar instead.
=> Disable dokka javadoc jars for publishing

CHANGELOG.md, core/src/commonIntegrationTest/kotlin/com/powersync/DatabaseTest.kt, core/src/commonMain/kotlin/com/powersync/db/PowerSyncDatabaseImpl.kt, core/src/commonMain/kotlin/com/powersync/db/Queries.kt, core/src/commonMain/kotlin/com/powersync/db/internal/InternalDatabaseImpl.kt
This fixes a bug where the `hasMore` value of `CrudBatch` was always false.
This adds a `triggerImmediately` parameter to the `onChange` API similar to the [Dart API](https://github.com/powersync-ja/sqlite_async.dart/blob/6d85217e30c61c3e51372b2304aec6ae1f1660b6/packages/sqlite_async/lib/src/sqlite_queries.dart#L86). Adding this makes it easy to avoid race conditions in consumers such as the Swift SDK.
=> CrudBatch hasMore + onChange improvement

.github/workflows/deploy.yml, docs/Release.md, gradle.properties
The `KMMBridgeGithubWorkflow` action builds and publishes the artifacts required by the Swift SDK. 
On a high level the workflow:
- Builds the binary artifacts and uploads them to Maven
- Updates the committed `Package.swift` file to point to these `binaryTarget`s.
- Pushes the updated changes to a temporary branch and tags the commit with a computed version tag. Swift consumers can then use SPM to checkout the repo at this tag to obtain the core frameworks.
The workflow automatically adds a patch suffix to the provided version string. This distinguishes the KMM release from other releases. This causes version mappings such as `1.0.0-BETA21` -> `1.0.0-BETA21.0`.
The workflow [broke](https://github.com/powersync-ja/powersync-kotlin/actions/runs/14756037385) when we updated the Kotlin SDK …
=> [Chore] Update KMM deploy action

CHANGELOG.md, gradle.properties
The previous failed KMM [publish](https://github.com/powersync-ja/powersync-kotlin/actions/runs/14756037385/job/41427039008) job already published some artifacts before it failed. This causes a new publish to [fail](https://github.com/powersync-ja/powersync-kotlin/actions/runs/14792437919/job/41534823355).
This bumps the package version in order to avoid package publishing conflicts.
=> chore: bump version

Package.swift, PowerSyncKotlin/build.gradle.kts
The kmmbridge Gradle plugin uses a Gradle `Zip` task to create a `.zip` archive of an XCFramework directory for the compiled Kotlin code.
On macOS, the layout of an XCFramework typically looks like this:
```
PowerSyncKotlin.xcframework/
├─ macos-arm64_x86_64/
│  ├─ Versions/
│  │  ├─ A/
│  │  │  ├─ .../
│  │  ├─ Current/    (symlink to ./A)
```
However, the Gradle `Zip` task does not support preserving symlinks when creating zip files. Instead, these files are copied into the uploaded archive. It looks like XCode is not consistently fine with this, sometimes attempting to `readlink` the `Current/` directory in the xcframework even when it is a regular directory. This fails, breaking macOS builds.
This PR applies a hack to the publishing logic for the `:PowerSyncKotlin` project that will …
=> Fix symlinks in generated XCFramework

CHANGELOG.md, core/src/commonIntegrationTest/kotlin/com/powersync/CrudTest.kt, core/src/commonMain/kotlin/com/powersync/db/crud/CrudEntry.kt, core/src/commonMain/kotlin/com/powersync/db/schema/Table.kt, gradle.properties
Benita pointed out that the `oldData` field in `CrudEntry` is inconsistent with the `trackPreviousValues` option. So, this renames it to `previousValues` for clarity.
This also bumps the version to `1.1.0`, I think we can start a release once this is merged.
=> Rename `oldData` in CRUD entries to `previousValues`

core/src/commonIntegrationTest/kotlin/com/powersync/sync/SyncProgressTest.kt, core/src/commonMain/kotlin/com/powersync/sync/SyncStream.kt, demos/supabase-todolist/gradle.properties, gradle.properties, plugins/build-plugin/src/main/kotlin/com/powersync/compile/ClangCompile.kt, plugins/build-plugin/src/main/kotlin/com/powersync/compile/CreateSqliteCInterop.kt, plugins/build-plugin/src/main/kotlin/com/powersync/compile/CreateStaticLibrary.kt, plugins/build-plugin/src/main/kotlin/com/powersync/compile/UnzipSqlite.kt, static-sqlite-driver/build.gradle.kts
On all native platforms we currently support, we compile and link a copy of SQLite statically (through the `:static-sqlite-driver` project).
The way the compilation is currently set up is a suboptimal, as it doesn't allow Gradle to cache outputs effectively:
1. We're using `dependsOn` to specify task dependencies, which is [not recommended](https://docs.gradle.org/current/userguide/best_practices_tasks.html#avoid_depends_on). We should specify file dependencies instead, as that allows Gradle to understand the dependencies better and allows for fine-grained build invalidation.
2. A lot of the compilation tasks we written using `Exec`, which does not support caching. To make the build easier to understand while also improving cache invalidation, I've extracted the tasks into independent …
=> Refactor SQLite compilation tasks

core-tests-android/src/androidTest/java/com/powersync/AndroidDatabaseTest.kt, core/src/androidMain/kotlin/com/powersync/DatabaseDriverFactory.android.kt
SQLite tries to write some temporary data, such as large intermediate materialized views or indexes, to the file system. For this, it attempts to use paths in `/tmp` or the current working directory. Due to sandboxing, both directories are unavailable on Android though. This can cause [errors that users were running into](https://discord.com/channels/1138230179878154300/1357681026939486369/1362417181802893482).
As a workaround, this overwrites the temporary directory to point to the cache directory from the app's `Context`.
=> Set temp_store_directory on Android

CHANGELOG.md, gradle.properties
Raise the version to `1.1.1` and add changelog entries for changes since `1.1.0`.
=> Prepare 1.1.1 release

plugins/build-plugin/src/main/kotlin/com/powersync/compile/ClangCompile.kt
At the moment, our SDK build process assumes that Apple toolchains exists at `/Applications/Xcode.app/Contents/Developer/`. That's not always the case though, and we shouldn't make that assumption. Instead, we can run `xcode-select -p` to obtain an installation to use. This changes the C compilation tasks (which have previously used a hardcoded path) to use the dynamic installation path instead.
=> Use xcode-select to find xcode installation

CHANGELOG.md, core/build.gradle.kts, core/src/androidMain/kotlin/com/powersync/sync/UserAgent.android.kt, core/src/jvmMain/kotlin/com/powersync/sync/UserAgent.jvm.kt, core/src/nativeMain/kotlin/com/powersync/sync/UserAgent.native.kt, gradle.properties
This adds a simple Gradle task generating a source set with a single file containing the version of the SDK. This is then imported when creating the user agent to always include the version.
Apart from that, this raises the version to 1.2.0 and prepares a release.
=> Include version number in user agent, prepare release

connectors/supabase/src/commonMain/kotlin/com/powersync/connector/supabase/SupabaseConnector.kt
interceptor was only capturing error codes when the HTTP status was exactly 400, but RLS violations from Supabase were coming with a different HTTP status code. For example fatal error [INSUFFICIENT PRIVILEGE 42501](https://github.com/powersync-ja/powersync-kotlin/blob/main/connectors/supabase/src/commonMain/kotlin/com/powersync/connector/supabase/SupabaseConnector.kt#L50) was 403.
closes #204
=> Update error handling to capture all 4xx responses

CHANGELOG.md, core/src/commonIntegrationTest/kotlin/com/powersync/sync/SyncIntegrationTest.kt, core/src/commonIntegrationTest/kotlin/com/powersync/testutils/TestUtils.kt, core/src/commonMain/kotlin/com/powersync/connectors/PowerSyncBackendConnector.kt, core/src/commonMain/kotlin/com/powersync/sync/SyncStream.kt, core/src/commonTest/kotlin/com/powersync/TestConnector.kt, core/src/commonTest/kotlin/com/powersync/sync/SyncStreamTest.kt
In the `PowerSyncBackendConnector` implementation, errors thrown in `fetchCredentials()` are currently swallowed silently, because:
1. We use a supervisor scope to launch jobs fetching credentials.
2. We then call `join()` on a `Job` instead of using a `Deferrable` and `await()`. `join()` just waits for the job to finish and, for supervisor scopes, doesn't rethrow exceptions.
3. So, `getCredentialsCached()` would silently return `null` on errors, without this information being surfaced to the user.
On Android, it also looks like errors in root coroutines that aren't handled will unconditionally kill the app, regardless of the supervisor scope present (I can reproduce https://github.com/powersync-ja/powersync-kotlin/issues/219 by simply throwing in a connector's `fetchCredentials` on …
=> Refactor fetching credentials

CHANGELOG.md, gradle.properties
Update the `LIBRARY_VERSION` properties entry for the 1.3.0 release. The biggest change is the addition of raw tables, along with two bugfixes.
=> Prepare 1.3.0 release

.github/workflows/docs-deploy.yml
This fixes the documentation build, and adds a CI step to run the building part of the docs on each PR (while still only deploying for `main`).
=> Fix documentation build

.github/workflows/docs-deploy.yml, .github/workflows/test.yml, build.gradle.kts, core/src/commonIntegrationTest/kotlin/com/powersync/sync/SyncIntegrationTest.kt, core/src/commonIntegrationTest/kotlin/com/powersync/testutils/TestUtils.kt, core/src/commonMain/kotlin/com/powersync/sync/SyncStream.kt, core/src/commonTest/kotlin/com/powersync/PowerSyncTestLogWriter.kt, settings.gradle.kts
This applies the develocity plugin (which isn't required to run Gradle build scans, but necessary to declare our acceptance of the build scan terms of service in code). Build scans are disabled by default, so a `--scan` invocation on the command line is necessary to upload them.
Then, this configures the docs and testing steps to create and upload scans, which the Gradle GH action helpfully [links under "build outcome"](https://github.com/powersync-ja/powersync-kotlin/actions/runs/16345689744).
=> Enable build scans

README.md, plugins/build-plugin/src/main/kotlin/dokka-convention.gradle.kts
This configures Dokka to add a source link for each documented member, which is very convenient to check out the implementation for those cases where the documentation alone doesn't provide enough information.
This also updates the readme to update supported targets and to link to the generated API docs more prominently.
=> Dokka: Link to source

.github/workflows/test.yml
The tests tasks are supposed to take a few minutes at most (macOS is the longest one and takes around 8 minutes). Recently, I've noticed that some test jobs seemingly run forever though. I think this can't really be an issue on our end since even individual tests are supposed to have timeouts on them, but I couldn't figure out a root cause yet (I hope it's not the build scan 🙃).
When we run into this issue, it's better to fail the run after 15 minutes instead of consuming resources for 6 hours.
=> Set timeout for CI

CHANGELOG.md, demos/android-supabase-todolist/build.gradle.kts, demos/supabase-todolist/iosApp/iosApp/Info.plist, gradle.properties, gradle/libs.versions.toml, persistence/build.gradle.kts
This updates the Kotlin compiler to 2.2.10 and updates dependencies. It also updates the version number to 1.5.0.
=> Prepare 1.5.0 release, update dependencies

.github/workflows/test.yml, core/src/commonIntegrationTest/kotlin/com/powersync/AttachmentsTest.kt, core/src/commonIntegrationTest/kotlin/com/powersync/sync/SyncIntegrationTest.kt, core/src/commonMain/kotlin/com/powersync/attachments/AttachmentQueue.kt, core/src/commonMain/kotlin/com/powersync/attachments/implementation/AttachmentContextImpl.kt, core/src/commonMain/kotlin/com/powersync/attachments/sync/SyncingService.kt, core/src/commonMain/kotlin/com/powersync/bucket/BucketStorage.kt, core/src/commonMain/kotlin/com/powersync/bucket/BucketStorageImpl.kt, core/src/commonMain/kotlin/com/powersync/sync/SyncStream.kt, gradle/libs.versions.toml
This updates the core extension to version 0.4.6 ([release notes](https://github.com/powersync-ja/powersync-sqlite-core/releases/tag/v0.4.6)).
A new feature in that version is that the Rust client can now be notified about connection events (like receiving headers but no body line yet, or the stream closing). This adopts that instead of handling the sync status update for `connecting` -> `connected` in Kotlin.
This also adds a few logs to debug the flaky attachment tests.
=> Update PowerSync core extension

.github/workflows/test.yml, CHANGELOG.md, README.md, compose/build.gradle.kts, gradle/libs.versions.toml, integrations/sqldelight-test-database/build.gradle.kts, integrations/sqldelight-test-database/src/commonMain/sqldelight/com/powersync/integrations/sqldelight/todos.sq, integrations/sqldelight/README.md, integrations/sqldelight/build.gradle.kts, integrations/sqldelight/gradle.properties, integrations/sqldelight/src/appleTest/kotlin/com/powersync/integrations/sqldelight/SqlDelightTest.apple.kt, integrations/sqldelight/src/commonIntegrationTest/kotlin/com/powersync/integrations/sqldelight/SqlDelightTest.kt, integrations/sqldelight/src/commonMain/kotlin/com/powersync/integrations/sqldelight/PowerSyncDriver.kt, integrations/sqldelight/src/jvmTest/kotlin/com/powersync/integrations/sqldelight/SqlDelightTest.jvm.kt, plugins/build-plugin/src/main/kotlin/com/powersync/plugins/utils/KmpUtils.kt, settings.gradle.kts
This adds a new project in the `integrations` folder that provides a single class: `PowerSyncDriver`. That class implements the `SqlDriver` interface from `SQLDelight` by forwarding queries and statements to an opened PowerSync database.
Additionally, query listeners in that driver are backed by `PowerSyncDatabase.onChange`, meaning that all changes between the original powersync database and the SQLDelight wrapper are visible to each other and cause reactive updates. An obvious but still pretty cool result is that updates from the sync client also trigger updates to flows in SQLDelight.
I've added a test project to run unit tests against a SQLDelight database, but no real example yet.
=> Add SQLDelight driver
